apiVersion: v1
kind: Pod
metadata:
  name: kiada
  labels:
    app: kiada
spec:
  containers:
  - name: kiada
    image: cooproton12/kiada:0.3
    imagePullPolicy: Always
    stdin: true
    ports:
    - containerPort: 8080
      name: http
